# Generated by Django 3.2.13 on 2022-06-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_product_img'),
        ('cart', '0003_auto_20220628_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
