# Generated by Django 3.2.13 on 2022-07-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_is_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_payed',
            new_name='payed',
        ),
    ]
