# Generated by Django 3.2.13 on 2022-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='refunded',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
