# Generated by Django 3.2.13 on 2022-06-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220613_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_quality', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.qualitytype'),
        ),
    ]
