# Generated by Django 3.2.13 on 2022-06-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220613_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
